services:
  - type: web
    name: jesska-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        value: mongodb+srv://<tu_usuario>:<tu_contraseña>@<cluster>.mongodb.net/<db>
      - key: JWT_SECRET
        value: 123456
      - key: CLIENT_URL
        value: https://jesska-frontend.onrender.com

  - type: web
    name: jesska-frontend
    env: node
    plan: free
    rootDir: frontend
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: API_BASE_URL
        value: https://jesska-backend.onrender.com
