services:
  - type: web
    name: jesska-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 4000
      - key: MONGO_URI
        sync: false
      - key: USER_DB
        sync: false
      - key: PASS_DB
        sync: false
      - key: DB_NAME
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: PASS_USER
        sync: false
      - key: APIKEY_NAME
        sync: false
      - key: APIKEY_PASS
        sync: false

  - type: web
    name: jesska-frontend
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
